project:
  type: website
  output-dir: docs

website:
  title: "Statistics CSEE"
  toc: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About us
    right: 
      - href: fr/index.fr.qmd
        text: Français
        
lang: en

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

