project:
  type: website
  output-dir: docs

website:
  title: "Statistics CSEE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - href: joinus.qmd
        text: Join
    right: 
      - href: fr/index.fr.qmd
        text: Français
        
lang: en

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

