project:
  type: website
  output-dir: ../docs/fr

website:
  title: "Statistique SCEE"
  navbar:
    left:
      - href: index.fr.qmd
        text: Accueil
      - href: about.fr.qmd
        text: À propos
    right: 
      - href: ../
        text: English

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

