---
title: "About"
---

Novel tools, approaches, and questions in ecology and evolution bring new analytical challenges, including handling larger amounts of data collected at finer and finer spatial and temporal scales. As a result, new methodologies are required to analyze the resulting data sets and to extract useful information and insights about the genes, populations, species, traits, communities, and ecosystems of interest. At the same time, statisticians and data scientists are developing novel techniques that can benefit ecological and evolutionary research. The goal of the Statistics Section is to advance the development, assessment, and application of statistical methods in ecology and evolution including the design of observational and experimental studies and the analysis of ecological and evolutionary data by promoting collaboration and discussion within the broad research communities of ecology, evolution, statistics, and data science in Canada. Recognizing the need for two-way communication, we aim both to educate the members of the Canadian Society for Ecology and Evolution (CSEE) about emerging analytical methodology and to teach the statistical community about new developments and needs of ecologists and evolutionary biologists. To this end, the Section organizes events that bring together diverse, interdisciplinary audiences from across the spectrums of ecology, evolution, statistics, and data science to promote new collaborations and foster new ideas that benefit all groups.
